services:

  Bundles\TwilioBundle\Controller\CallController:
    arguments:
      - '@Bundles\TwilioBundle\Manager\TwilioCallManager'
      - '@logger'
    tags:
      - controller.service_arguments

  Bundles\TwilioBundle\Controller\ReplyController:
    arguments:
      - '@Bundles\TwilioBundle\Service\Twilio'
      - '@logger'
    tags:
      - controller.service_arguments

  Bundles\TwilioBundle\Controller\StatusController:
    arguments:
      - '@Bundles\TwilioBundle\Manager\TwilioMessageManager'
      - '@Bundles\TwilioBundle\Manager\TwilioStatusManager'
      - '@event_dispatcher'
      - '@logger'
    tags:
      - controller.service_arguments
