services:

  Bundles\TwilioBundle\Controller\ReplyController:
    arguments:
      - '@Bundles\TwilioBundle\SMS\Twilio'
    tags:
      - controller.service_arguments

  Bundles\TwilioBundle\Controller\StatusController:
    arguments:
      - '@Bundles\TwilioBundle\Manager\TwilioMessageManager'
      - '@Bundles\TwilioBundle\Manager\TwilioStatusManager'
      - '@event_dispatcher'
    tags:
      - controller.service_arguments
