services:

  Bundles\TwilioBundle\Manager\TwilioMessageManager:
    arguments:
      - '@Bundles\TwilioBundle\Repository\TwilioMessageRepository'
      - '@Bundles\TwilioBundle\Service\Twilio'
      - '@event_dispatcher'
      - '@router'
      - '@logger'

  Bundles\TwilioBundle\Manager\TwilioCallManager:
    arguments:
      - '@Bundles\TwilioBundle\Repository\TwilioCallRepository'
      - '@Bundles\TwilioBundle\Service\Twilio'
      - '@event_dispatcher'
      - '@router'
      - '@logger'

  Bundles\TwilioBundle\Manager\TwilioStatusManager:
    arguments:
      - '@Bundles\TwilioBundle\Repository\TwilioStatusRepository'
      - '@event_dispatcher'
