services:

  Bundles\TwilioBundle\Repository\TwilioMessageRepository:
    arguments:
      - '@Doctrine\Common\Persistence\ManagerRegistry'

  Bundles\TwilioBundle\Repository\TwilioCallRepository:
    arguments:
      - '@Doctrine\Common\Persistence\ManagerRegistry'

  Bundles\TwilioBundle\Repository\TwilioStatusRepository:
    arguments:
      - '@Doctrine\Common\Persistence\ManagerRegistry'
