services:

  Bundles\TwilioBundle\Repository\TwilioMessageRepository:
    arguments:
      - '@Doctrine\Common\Persistence\ManagerRegistry'
      - 'Bundles\TwilioBundle\Entity\TwilioMessage'

  Bundles\TwilioBundle\Repository\TwilioStatusRepository:
    arguments:
      - '@Doctrine\Common\Persistence\ManagerRegistry'
      - 'Bundles\TwilioBundle\Entity\TwilioStatus'
