services:

  Bundles\TwilioBundle\Service\Twilio:
    arguments:
      - '@router'
      - '@event_dispatcher'
      - '@Bundles\TwilioBundle\Manager\TwilioMessageManager'
      - '@Bundles\TwilioBundle\Manager\TwilioCallManager'
      - '@logger'
