services:

  Bundles\SandboxBundle\Controller\AnonymizeController:
    public: true
    arguments:
      - '@Bundles\SandboxBundle\Manager\AnonymizeManager'

  Bundles\SandboxBundle\Controller\FakeEmailController:
    public: true
    arguments:
      - '@Bundles\SandboxBundle\Manager\FakeEmailManager'
      - '@App\Manager\VolunteerManager'

  Bundles\SandboxBundle\Controller\FakeSmsController:
    public: true
    arguments:
      - '@Bundles\SandboxBundle\Manager\FakeSmsManager'
      - '@App\Manager\MessageManager'
      - '@App\Manager\VolunteerManager'

