imports:

parameters:
    password_login.base.type.class: 'Bundles\PasswordLoginBundle\Base\BaseType'
    password_login.connect.type.class: 'Bundles\PasswordLoginBundle\Form\Type\ConnectType'
    password_login.forgot_password.type.class: 'Bundles\PasswordLoginBundle\Form\Type\ForgotPasswordType'
    password_login.change_password.type.class: 'Bundles\PasswordLoginBundle\Form\Type\ChangePasswordType'
    password_login.registration.type.class: 'Bundles\PasswordLoginBundle\Form\Type\RegistrationType'
    password_login.profile.type.class: 'Bundles\PasswordLoginBundle\Form\Type\ProfileType'

services:

    password_login.base.type:
        class: '%password_login.base.type.class%'
        abstract: true
        calls:
          - [setContainer, ["@service_container"]]

    password_login.connect.type:
        class: '%password_login.connect.type.class%'
        parent: password_login.base.type
        tags:
           - { name: form.type }

    password_login.forgot_password.type:
        class: '%password_login.forgot_password.type.class%'
        parent: password_login.base.type
        tags:
           - { name: form.type }

    password_login.change_password.type:
        class: '%password_login.change_password.type.class%'
        parent: password_login.base.type
        tags:
           - { name: form.type }

    password_login.registration.type:
        class: '%password_login.registration.type.class%'
        parent: password_login.base.type
        tags:
           - { name: form.type }

    password_login.profile.type:
        class: '%password_login.profile.type.class%'
        parent: password_login.base.type
        tags:
           - { name: form.type }
