parameters:
  password_login.base.service.class: 'Bundles\PasswordLoginBundle\Base\BaseService'
  password_login.provider.user.class: 'Bundles\PasswordLoginBundle\Security\Provider\UserProvider'
  password_login.authenticator.form_login.class: 'Bundles\PasswordLoginBundle\Security\Authenticator\FormLoginAuthenticator'
  password_login.mail.service.class: 'Bundles\PasswordLoginBundle\Services\Mail'

services:

  password_login.base.service:
    class: '%password_login.base.service.class%'
    abstract: true
    public: true
    calls:
      - [setContainer, ['@service_container']]

  password_login.authenticator.form_login:
    class: '%password_login.authenticator.form_login.class%'
    calls:
      - [setContainer, ['@service_container']]

  password_login.mail.service:
    class: '%password_login.mail.service.class%'
    parent: password_login.base.service
