
runtime: php72

readiness_check:
  app_start_timeout_sec: 3600

runtime_config:
  document_root: public
  front_controller_file: public/index.php
  enable_stackdriver_integration: true

env_variables:

handlers:
  - url: /build
    static_dir: public/build
  - url: /bundles
    static_dir: public/bundles
  - url: /(.*\.(ico|txt|gif|png|jpg))$
    static_files: public/\1
    upload: public/.*\.(ico|txt|gif|png|jpg)$

instance_class: F2

automatic_scaling:
  max_instances: 5
  target_cpu_utilization: 0.9
