controllers:
    resource: ../../src/Controller/
    type: annotation

password_login:
    resource: '@PasswordLoginBundle/Controller/'
    type: annotation

sandbox:
    resource: '@SandboxBundle/Controller/'
    type: annotation
    prefix: /sandbox
    name_prefix: sandbox_
