api:
  resource: '@ApiBundle/Controller/'
  type: annotation

controllers:
  resource: ../../src/Controller/
  type: annotation

password_login:
  resource: '@PasswordLoginBundle/Controller/'
  type: annotation

twilio:
  resource: '@TwilioBundle/Controller/'
  type: annotation
