imports:

parameters:
    password_login.base.command.class: 'Bundles\PasswordLoginBundle\Base\BaseCommand'
    password_login.user_admin.command.class: 'Bundles\PasswordLoginBundle\Command\UserAdminCommand'
    password_login.user_trust.command.class: 'Bundles\PasswordLoginBundle\Command\UserTrustCommand'
    password_login.user_verify.command.class: 'Bundles\PasswordLoginBundle\Command\UserVerifyCommand'
    password_login.user_list.command.class: 'Bundles\PasswordLoginBundle\Command\UserListCommand'
    password_login.user_cron.command.class: 'Bundles\PasswordLoginBundle\Command\UserCronCommand'

services:

    password_login.base.command:
        class: '%password_login.base.command.class%'
        abstract: true
        public: true
        calls:
          - [setContainer, ["@service_container"]]

    password_login.user_admin.command:
        class: '%password_login.user_admin.command.class%'
        parent: password_login.base.command
        tags:
          - { name: console.command }

    password_login.user_trust.command:
        class: '%password_login.user_trust.command.class%'
        parent: password_login.base.command
        tags:
          - { name: console.command }

    password_login.user_verify.command:
        class: '%password_login.user_verify.command.class%'
        parent: password_login.base.command
        tags:
          - { name: console.command }

    password_login.user_list.command:
        class: '%password_login.user_list.command.class%'
        parent: password_login.base.command
        tags:
          - { name: console.command }

    password_login.user_cron.command:
        class: '%password_login.user_cron.command.class%'
        parent: password_login.base.command
        tags:
          - { name: console.command }
