imports:

parameters:
  password_login.listener.exception.class: 'Bundles\PasswordLoginBundle\EventListener\CsrfExceptionListener'

services:

  password_login.listener.exception:
    class: '%password_login.listener.exception.class%'
    arguments: ['@twig']
    tags:
    - { name: kernel.event_listener, event: kernel.exception }
