parameters:
  communication.processor: 'App\Communication\Processor\SimpleProcessor'

services:
  App\Provider\SMS\SMSProvider:
    class: 'Bundles\SandboxBundle\Provider\FakeSmsProvider'
    arguments: ['@doctrine']
    public: true

  App\Provider\Email\EmailProvider:
    class: 'Bundles\SandboxBundle\Provider\FakeEmailProvider'
    arguments: ['@doctrine']
    public: true
